# Generated by Django 4.0.3 on 2022-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.IntegerField()),
                ('emp_email', models.CharField(max_length=50)),
            ],
        ),
    ]
